### ISSUE TITLE
Intersect function logic issue

### ISSUE THREAD

**Issue by peiliou** [Rajalo/Triangle-Intersect-User-Interface#1]
There is an earlier logic issue that's still not fixed: Intersect(Vertex a, Vertex b, Vertex c, Vertex d) always returns true.

Reference on piazza: [https://piazza.com/class/ksggasojoko7hr?cid=38_f2](https://piazza.com/class/ksggasojoko7hr?cid=38_f2), and I can confirm this still exists.

**Comment by Rajalo** [comment]
Thank you Pei for pointing this out!
